### ISSUE TITLE
Running `neotest.run.run({suite = true})` tries to run tests for dependencies

### ISSUE THREAD

**Issue by jonathanballs** [jfpedroza/neotest-elixir#39] opened 2024-06-20 15:45 UTC
When I run `neotest.run.run({suite = true})`, it seems that `neotest-elixir` is also trying to compile and run test files from my dependencies. In the case below, a failing compilation of a dependencies' test is causing the whole suite to break. I assume this is not expected behaviour...

Perhaps we can filter out all tests in `mix_root/deps/`. I'm not sure how complicated this is with umbrella apps and so forth.

![Screenshot 2024-06-20 at 16 41 09](https://github.com/jfpedroza/neotest-elixir/assets/4366510/189c0168-5ab5-4701-bd66-a06d742074ef)

**Comment by jfpedroza** [comment] 2024-06-20 20:40
Duplicate of #37

**Closed as completed** 2024-06-21 10:48 UTC
